#ifndef SMARTGOLDDCAPRO_DCA_ENGINE_MQH
#define SMARTGOLDDCAPRO_DCA_ENGINE_MQH

#include <SmartGoldDCAPro/Core/Types.mqh>
#include <SmartGoldDCAPro/Core/Inputs.mqh>
#include <SmartGoldDCAPro/Core/RiskManager.mqh>

#include <SmartGoldDCAPro/Risk/SmartLotCalculator.mqh>

#include <SmartGoldDCAPro/Trade/PositionManager.mqh>

#include <SmartGoldDCAPro/Market/MarketState.mqh>
#include <SmartGoldDCAPro/Market/MarketAnalyzer.mqh>

#include <SmartGoldDCAPro/DCA/AdaptiveGridEngine.mqh>

//+------------------------------------------------------------------+
//| SmartGoldDCAPro Framework v2.0 - DCA Engine                      |
//| Evaluates whether another basket position may be added           |
//+------------------------------------------------------------------+
class CDCAEngine
{
private:
   CPositionManager    *m_positions;
   CRiskManager        *m_risk;
   CMarketAnalyzer     *m_market;
   CAdaptiveGridEngine *m_grid;
   CSmartLotCalculator *m_lotCalculator;

   bool m_initialized;

   double m_lastGridPoints;
   double m_lastATRPoints;
   double m_lastAdversePoints;
   double m_lastNextLot;
   double m_lastMarginLevel;
   double m_lastFreeMargin;

   int  m_lastRiskScore;
   int  m_lastNextOrderNumber;
   bool m_lastSmartSafetyActive;

   ENUM_POSITION_TYPE m_lastDirection;

   string m_lastReason;

   //+----------------------------------------------------------------+
   //| Reset values generated by the latest evaluation                |
   //+----------------------------------------------------------------+
   void ResetEvaluation()
   {
      m_lastGridPoints =
         0.0;

      m_lastATRPoints =
         0.0;

      m_lastAdversePoints =
         0.0;

      m_lastNextLot =
         0.0;

      m_lastMarginLevel =
         0.0;

      m_lastFreeMargin =
         0.0;

      m_lastRiskScore =
         0;

      m_lastNextOrderNumber =
         0;

      m_lastSmartSafetyActive =
         false;

      m_lastDirection =
         POSITION_TYPE_BUY;

      m_lastReason =
         "DCA has not been evaluated.";
   }

   //+----------------------------------------------------------------+
   //| Store a rejected DCA reason                                    |
   //+----------------------------------------------------------------+
   bool Reject(
      string &reason,
      const string message
   )
   {
      reason =
         message;

      m_lastReason =
         message;

      return false;
   }

   //+----------------------------------------------------------------+
   //| Verify all dependencies                                        |
   //+----------------------------------------------------------------+
   bool ModulesReady() const
   {
      return
         m_initialized &&
         m_positions     != NULL &&
         m_risk          != NULL &&
         m_market        != NULL &&
         m_grid          != NULL &&
         m_lotCalculator != NULL;
   }

   //+----------------------------------------------------------------+
   //| Determine whether Smart Safety applies to the next order       |
   //+----------------------------------------------------------------+
   bool IsSmartSafetyActive(
      const int nextOrderNumber
   ) const
   {
      if(!InpEnableSmartSafety)
         return false;

      return
         nextOrderNumber >=
         InpSmartSafetyStartOrder;
   }

   //+----------------------------------------------------------------+
   //| Calculate the lot for the next DCA order                       |
   //+----------------------------------------------------------------+
   double CalculateNextLot(
      const double lastVolume,
      const bool smartSafetyActive
   ) const
   {
      if(m_risk == NULL ||
         m_lotCalculator == NULL)
      {
         return 0.0;
      }

      if(lastVolume <= 0.0)
         return 0.0;

      // Manual mode uses the explicitly configured DCA lot.
      if(InpDCAControlMode ==
         DCA_CONTROL_MANUAL)
      {
         return
            m_risk.NormalizeLot(
               InpManualDCALot
            );
      }

      // Smart Safety applies drawdown and margin reduction factors.
      if(smartSafetyActive)
      {
         return
            m_lotCalculator.CalculateNextLot(
               lastVolume,
               InpLotMultiplier,
               InpMaximumLot,
               m_risk.CurrentDrawdownPercent()
            );
      }

      double calculatedLot =
         lastVolume *
         InpLotMultiplier;

      calculatedLot =
         MathMin(
            calculatedLot,
            InpMaximumLot
         );

      return
         m_risk.NormalizeLot(
            calculatedLot
         );
   }

   //+----------------------------------------------------------------+
   //| Calculate the required DCA distance                            |
   //+----------------------------------------------------------------+
   double CalculateGridPoints(
      const SMarketAnalysis &marketAnalysis
   )
   {
      if(InpDCAControlMode ==
         DCA_CONTROL_MANUAL)
      {
         return
            m_grid.ManualGrid(
               InpManualDCADistancePoints
            );
      }

      if(InpDCAControlMode ==
         DCA_CONTROL_FIXED)
      {
         return
            m_grid.ManualGrid(
               InpDCADistancePoints
            );
      }

      return
         m_grid.Calculate(
            marketAnalysis
         );
   }

   //+----------------------------------------------------------------+
   //| Calculate price movement against the basket direction          |
   //+----------------------------------------------------------------+
   bool CalculateAdversePoints(
      const ENUM_POSITION_TYPE direction,
      const double latestOpenPrice,
      const SMarketAnalysis &marketAnalysis,
      double &adversePoints,
      string &reason
   ) const
   {
      adversePoints =
         0.0;

      reason =
         "";

      double point =
         SymbolInfoDouble(
            m_positions.Symbol(),
            SYMBOL_POINT
         );

      if(point <= 0.0)
      {
         reason =
            "Invalid symbol point.";

         return false;
      }

      if(direction ==
         POSITION_TYPE_BUY)
      {
         adversePoints =
            (
               latestOpenPrice -
               marketAnalysis.bid
            ) /
            point;

         return true;
      }

      if(direction ==
         POSITION_TYPE_SELL)
      {
         adversePoints =
            (
               marketAnalysis.ask -
               latestOpenPrice
            ) /
            point;

         return true;
      }

      reason =
         "Unsupported basket direction.";

      return false;
   }

public:
   CDCAEngine()
   {
      m_positions =
         NULL;

      m_risk =
         NULL;

      m_market =
         NULL;

      m_grid =
         NULL;

      m_lotCalculator =
         NULL;

      m_initialized =
         false;

      ResetEvaluation();

      m_lastReason =
         "DCA Engine is not initialized.";
   }

   //+----------------------------------------------------------------+
   //| Connect all DCA dependencies                                   |
   //+----------------------------------------------------------------+
   void Initialize(
      CPositionManager &positions,
      CRiskManager &risk,
      CMarketAnalyzer &market,
      CAdaptiveGridEngine &grid,
      CSmartLotCalculator &lotCalculator
   )
   {
      m_positions =
         &positions;

      m_risk =
         &risk;

      m_market =
         &market;

      m_grid =
         &grid;

      m_lotCalculator =
         &lotCalculator;

      m_initialized =
         true;

      ResetEvaluation();

      m_lastReason =
         "DCA Engine initialized.";
   }

   bool IsInitialized() const
   {
      return ModulesReady();
   }

   //+----------------------------------------------------------------+
   //| Evaluate whether another DCA position may be added             |
   //| This function does not submit an order                         |
   //+----------------------------------------------------------------+
   bool ShouldAddPosition(
      ENUM_POSITION_TYPE &direction,
      double &nextLot,
      string &reason
   )
   {
      ResetEvaluation();

      direction =
         POSITION_TYPE_BUY;

      nextLot =
         0.0;

      reason =
         "";

      if(!ModulesReady())
      {
         return Reject(
            reason,
            "DCA Engine dependencies are not initialized."
         );
      }

      if(!InpEnableDCA)
      {
         return Reject(
            reason,
            "DCA is disabled by input."
         );
      }

      int positionCount =
         m_positions.CountAll();

      if(positionCount <= 0)
      {
         return Reject(
            reason,
            "No active basket."
         );
      }

      if(positionCount >=
         InpMaximumDCALevels)
      {
         return Reject(
            reason,
            "Maximum DCA levels reached."
         );
      }

      m_lastNextOrderNumber =
         positionCount + 1;

      m_lastSmartSafetyActive =
         IsSmartSafetyActive(
            m_lastNextOrderNumber
         );

      if(!m_positions.GetBasketDirection(
            direction
         ))
      {
         return Reject(
            reason,
            "Mixed BUY/SELL basket is not supported."
         );
      }

      m_lastDirection =
         direction;

      SMarketAnalysis marketAnalysis;

      if(!m_market.Read(
            marketAnalysis
         ))
      {
         return Reject(
            reason,
            "Market Analysis is unavailable."
         );
      }

      if(!marketAnalysis.valid)
      {
         return Reject(
            reason,
            "Market Analysis is invalid."
         );
      }

      m_lastATRPoints =
         marketAnalysis.atrPoints;

      m_lastGridPoints =
         CalculateGridPoints(
            marketAnalysis
         );

      if(m_lastGridPoints <= 0.0)
      {
         return Reject(
            reason,
            "Calculated DCA grid is invalid. " +
            m_grid.LastReason()
         );
      }

      m_lastMarginLevel =
         m_lotCalculator.CurrentMarginLevel();

      m_lastFreeMargin =
         m_lotCalculator.CurrentFreeMargin();

      m_lastRiskScore =
         m_lotCalculator.CalculateRiskScore(
            positionCount,
            (int)MathRound(
               marketAnalysis.spreadPoints
            ),
            marketAnalysis.atrPoints,
            InpMaximumSpreadPoints,
            InpHighVolatilityATRPoints
         );

      //==============================================================
      // SMART SAFETY: RISK SCORE
      //==============================================================

      if(m_lastSmartSafetyActive &&
         InpSmartSafetyUseRiskScore &&
         m_lastRiskScore >
         InpMaximumRiskScoreForDCA)
      {
         return Reject(
            reason,
            "DCA blocked by Smart Risk Score. Current=" +
            IntegerToString(
               m_lastRiskScore
            ) +
            ", maximum=" +
            IntegerToString(
               InpMaximumRiskScoreForDCA
            ) +
            "."
         );
      }

      //==============================================================
      // SMART SAFETY: HIGH VOLATILITY
      //==============================================================

      if(m_lastSmartSafetyActive &&
         InpSmartSafetyUseHighVolatilityBlock &&
         InpBlockDCAInHighVolatility &&
         marketAnalysis.regime ==
         MARKET_REGIME_HIGH_VOLATILITY)
      {
         return Reject(
            reason,
            "DCA blocked by high-volatility protection."
         );
      }

      //==============================================================
      // SMART SAFETY: MARGIN
      //==============================================================

      if(m_lastSmartSafetyActive &&
         InpSmartSafetyUseMarginProtection)
      {
         string marginReason;

         if(!m_lotCalculator.IsMarginSafe(
               InpMinimumMarginLevelPercent,
               InpMinimumFreeMarginMoney,
               marginReason
            ))
         {
            return Reject(
               reason,
               "DCA blocked by margin protection. " +
               marginReason
            );
         }
      }

      double latestPrice =
         0.0;

      double latestVolume =
         0.0;

      datetime latestTime =
         0;

      ENUM_POSITION_TYPE latestType =
         POSITION_TYPE_BUY;

      if(!m_positions.GetLatestPosition(
            latestPrice,
            latestVolume,
            latestType,
            latestTime
         ))
      {
         return Reject(
            reason,
            "Cannot read the latest basket position."
         );
      }

      if(latestType != direction)
      {
         return Reject(
            reason,
            "Latest position direction does not match the basket."
         );
      }

      string adverseReason;

      if(!CalculateAdversePoints(
            direction,
            latestPrice,
            marketAnalysis,
            m_lastAdversePoints,
            adverseReason
         ))
      {
         return Reject(
            reason,
            adverseReason
         );
      }

      if(m_lastAdversePoints <
         m_lastGridPoints)
      {
         return Reject(
            reason,
            "DCA distance not reached. Current=" +
            DoubleToString(
               m_lastAdversePoints,
               1
            ) +
            ", required=" +
            DoubleToString(
               m_lastGridPoints,
               1
            ) +
            "."
         );
      }

      nextLot =
         CalculateNextLot(
            latestVolume,
            m_lastSmartSafetyActive
         );

      m_lastNextLot =
         nextLot;

      if(nextLot <= 0.0)
      {
         return Reject(
            reason,
            "Next DCA lot was blocked by lot or safety protection."
         );
      }

      reason =
         "DCA conditions are valid. Direction=" +
         SGDPPositionTypeName(
            direction
         ) +
         ", order=" +
         IntegerToString(
            m_lastNextOrderNumber
         ) +
         ", grid=" +
         DoubleToString(
            m_lastGridPoints,
            1
         ) +
         ", adverse=" +
         DoubleToString(
            m_lastAdversePoints,
            1
         ) +
         ", lot=" +
         DoubleToString(
            nextLot,
            2
         ) +
         ", Smart Safety=" +
         (
            m_lastSmartSafetyActive
            ? "ON"
            : "OFF"
         ) +
         ".";

      m_lastReason =
         reason;

      return true;
   }

   string ControlModeName() const
   {
      switch(InpDCAControlMode)
      {
         case DCA_CONTROL_MANUAL:
            return "MANUAL";

         case DCA_CONTROL_FIXED:
            return "FIXED";

         case DCA_CONTROL_ADAPTIVE:
            return "ADAPTIVE";
      }

      return "UNKNOWN";
   }

   double LastGridPoints() const
   {
      return m_lastGridPoints;
   }

   double LastATRPoints() const
   {
      return m_lastATRPoints;
   }

   double LastAdversePoints() const
   {
      return m_lastAdversePoints;
   }

   double LastNextLot() const
   {
      return m_lastNextLot;
   }

   double LastMarginLevel() const
   {
      return m_lastMarginLevel;
   }

   double LastFreeMargin() const
   {
      return m_lastFreeMargin;
   }

   int LastRiskScore() const
   {
      return m_lastRiskScore;
   }

   int LastNextOrderNumber() const
   {
      return m_lastNextOrderNumber;
   }

   bool LastSmartSafetyActive() const
   {
      return m_lastSmartSafetyActive;
   }

   ENUM_POSITION_TYPE LastDirection() const
   {
      return m_lastDirection;
   }

   string LastReason() const
   {
      return m_lastReason;
   }

   void Reset()
   {
      ResetEvaluation();

      m_lastReason =
         "DCA Engine reset.";
   }
};

#endif