#ifndef SMARTGOLDDCAPRO_TYPES_MQH
#define SMARTGOLDDCAPRO_TYPES_MQH
enum ENUM_TRADE_SIGNAL{ SIGNAL_NONE=0,SIGNAL_BUY=1,SIGNAL_SELL=-1 };
enum ENUM_DIRECTION_MODE{ DIRECTION_AUTO=0,DIRECTION_BUY_ONLY=1,DIRECTION_SELL_ONLY=2 };
#endif
