#ifndef SMARTGOLDDCAPRO_TYPES_MQH
#define SMARTGOLDDCAPRO_TYPES_MQH
<<<<<<< HEAD

enum ENUM_TRADE_SIGNAL
{
   SIGNAL_NONE = 0,
   SIGNAL_BUY  = 1,
   SIGNAL_SELL = -1
};

enum ENUM_DIRECTION_MODE
{
   DIRECTION_AUTO      = 0,
   DIRECTION_BUY_ONLY  = 1,
   DIRECTION_SELL_ONLY = 2
};

enum ENUM_DCA_CONTROL_MODE
{
   DCA_CONTROL_SMART  = 0,
   DCA_CONTROL_MANUAL = 1
};

=======
enum ENUM_TRADE_SIGNAL{ SIGNAL_NONE=0,SIGNAL_BUY=1,SIGNAL_SELL=-1 };
enum ENUM_DIRECTION_MODE{ DIRECTION_AUTO=0,DIRECTION_BUY_ONLY=1,DIRECTION_SELL_ONLY=2 };
>>>>>>> a6502552adb3f6daad7bbaab71976b01460fd24e
#endif
